name: web3_dart_client
description: Web3 Ethereum client for Dart and Flutter
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web3dart: ^2.7.1
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.0
